### ISSUE TITLE
Start with "Understanding/Research"

### ISSUE THREAD

**Issue by heyjerrybecker** [open-organization/open-decision-framework#37]

**Comment by beckerjs** [comment]
Red Hat believes in a human-centric approach to product development, leadership, and decision-making. And truly human-centered approach always starts with understanding (or empathy). As such, I think it might be worth reordering the steps (or phases) of the Open Decision Framework.

Right now, the steps are as follows:
-Ideation
-Planning and research
-Design, development, and testing
-Launch

Starting with ideation, however, might lead to building the wrong thing. I think the steps should be:
-Research & Understanding
-Ideation
-Design, prototype, and test
-Develop & Launch

In my proposed steps, ideation only comes after a problem has been validated through research and understanding. The context gained in this phase will improve the quality of ideas generated in the next phase. Also, the 3rd step replaces "development" with "prototype." We should prototype ideas and get feedback before we take the time to develop so we can validate our solutions before spending the time to fully realize them. This will help buy down the risk of developing the wrong thing, as it allows us to course-correct our prototype ideas with real users prior to investing in the time/effort to develop. We should only develop once we have a validated prototype.

**Comment by ruhbehka** [comment]
How funny, as luck would have it, @mizmo and I were just talking about
this. More to come, when we get around to it... :)

**Comment by ruhbehka** [comment]
We agreed that there's a need for some kind of supplemental guidance for
design-oriented projects - @mizmo has been working on this on her own for a
while, and hopes to have a draft to share in the next year. I also noted
that we have an internal Design Thinking model developed at Red Hat years
ago, and it can be confusing to figure out when to apply that vs. the Open
Decision Framework, so we need to try to untangle that and offer guidance
on how the approaches are complementary (and when one might be better than
the other). This is all happening at the same time as I'm trying to figure
out how to add in some "change adoption" tactics for those who join
mid-decision or post-decision (or who don't get involved with the decision,
but then struggle to implement it afterward). Also, some stuff aimed at
helping the decision-maker create a horse rather than a camel, despite
getting input that would nudge them toward the camel (the old adage about a
camel is a horse designed by a committee)... thinking through how to check
yourself as you incorporate ideas and address use cases, that the overall
user experience isn't suffering (and that it will be as frictionless for
new users in the future as for those who you're designing for today). Lots
of learnings over the past few years that we need to figure out how to
incorporate into a refreshed version. The challenge is always, time time
time. :)

**Comment by ruhbehka** [comment]
Nah, with many eyes, all bugs are shallow. :-) It’s the “getting the ideas
out of multiple people’s heads and into a draft” part that is the scary
piece, haha.
-- 
-----

Rebecca Fernandez

She / Her / Hers

Principal Program Manager, Scaling Our Open Organization

Red Hat <https://www.redhat.com>


M: +1-919-931-4957
<https://www.redhat.com>

**Comment by rolfedh** [comment]
@ruhbehka @mizmo It seems like we should create a draft to start receiving people's ideas! How do we do that?

**Comment by ruhbehka** [comment]
You could create an open issue on GitHub, where people can add their ideas
and suggestions... that's generally how I track external and internal ideas
or RFEs that I can't easily resolve right away.

**Comment by jimmysjolund** [comment]
5 years later and with the move of the community version to the Open Organization I think we will drop the design approach or version of the ODF at this time. If anyone have any material or knowledge of the work that was ongoing, do bring it up again!
